import { parse } from '@babel/parser'
import _traverse from '@babel/traverse'
import * as t from '@babel/types'
import { relative } from 'node:path'
import { cwd } from 'node:process'

// @babel/traverse ships as CJS; normalise the default export for ESM contexts
const traverse = (typeof _traverse === 'function'
  ? _traverse
  : (_traverse as any).default) as typeof _traverse

interface Injection {
  /** Byte offset in the source where we insert the attribute */
  offset: number
  value: string
}

/**
 * Parses JSX source, collects insertion points for data-spoon-loc, then
 * applies them as pure string splices — the original code is never
 * regenerated by Babel, so TypeScript/TSX syntax stays bit-for-bit intact.
 */
export function transformWithLocation(
  source: string,
  filePath: string,
): { code: string; map: null } | undefined {
  const relPath = relative(cwd(), filePath)

  let ast: ReturnType<typeof parse>
  try {
    ast = parse(source, {
      sourceType: 'module',
      plugins: ['jsx', 'typescript'],
      sourceFilename: filePath,
    })
  } catch {
    return undefined
  }

  const injections: Injection[] = []

  traverse(ast, {
    JSXOpeningElement(nodePath) {
      const nameNode = nodePath.node.name
      // Only inject on intrinsic (lowercase) elements — HTML tags, not components
      if (!t.isJSXIdentifier(nameNode)) return
      if (nameNode.name[0] !== nameNode.name[0].toLowerCase()) return

      if (!nodePath.node.loc || nodePath.node.start == null) return

      // Don't double-inject
      const alreadyHas = nodePath.node.attributes.some(
        (a) => t.isJSXAttribute(a) && t.isJSXIdentifier(a.name) && a.name.name === 'data-spoon-loc',
      )
      if (alreadyHas) return

      const { line, column } = nodePath.node.loc.start
      const locValue = `${relPath}:${line}:${column}`

      // Find the insertion point: right after the tag name in the source.
      // e.g. `<div` → insert after the `v` character.
      // nodePath.node.start points to `<`, name length gives us the tag end.
      const insertAt = nodePath.node.start + 1 + nameNode.name.length

      injections.push({
        offset: insertAt,
        value: ` data-spoon-loc="${locValue}"`,
      })
    },
  })

  if (injections.length === 0) return undefined

  // Apply injections back-to-front so offsets stay valid
  injections.sort((a, b) => b.offset - a.offset)

  let result = source
  for (const { offset, value } of injections) {
    result = result.slice(0, offset) + value + result.slice(offset)
  }

  return { code: result, map: null }
}
